<?php

/**
 * PlugintpyProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintpyProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintpyProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintpyProduct');
    }
}