<?php

/**
 * PlugintpyTaxClassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintpyTaxClassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintpyTaxClassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintpyTaxClass');
    }
}