<?php

/**
 * PlugintpyOrderOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintpyOrderOrderStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintpyOrderOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintpyOrderOrderState');
    }
}