<?php

/**
 * PlugintpyStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintpyStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintpyStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintpyState');
    }
}