<?php

/**
 * PlugintpyTaxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintpyTaxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintpyTaxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintpyTax');
    }
}