<?php

/**
 * PlugintpyUserCartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintpyUserCartTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintpyUserCartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintpyUserCart');
    }
}