<?php

/**
 * PlugintpyOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintpyOrderItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintpyOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintpyOrderItem');
    }
}