<?php

/**
 * PlugintpyOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintpyOrderStateTable extends tpyStateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintpyOrderStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintpyOrderState');
    }
}