<?php

/**
 * PlugintpyCartItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintpyCartItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintpyCartItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintpyCartItem');
    }
}