tpyOrderState:
  inheritance:
    extends:   tpyState
    type:      column_aggregation
    keyField:  type
    keyValue:  'tpyOrderState'

tpyState:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:        string(50)
    description: text


